# Generated by Django 5.1.2 on 2024-12-13 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_bankaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
