# Generated by Django 5.1.2 on 2024-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_historicalbankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="description",
            field=models.CharField(default="asdasd", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbankaccount",
            name="description",
            field=models.CharField(default="asdasdasd", max_length=255),
            preserve_default=False,
        ),
    ]
