# Generated by Django 5.1.2 on 2024-12-13 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_bankaccount_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "bank_account",
                "verbose_name_plural": "bank_accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbankaccount",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical bank_account",
                "verbose_name_plural": "historical bank_accounts",
            },
        ),
    ]
